input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "model/models/model.pkl"
metric_path: "data/metrics/metrics.json"
validation_dataset_path: "data/processed/val_df.csv"
splitting_params:
  val_size: 0.2
  random_state: 3
train_params:
  model_type: "RandomForest"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
    - "ca"
  features_to_drop:
    - "trestbps"
  target_col: "condition"